<a href="https://colab.research.google.com/github/Aman05gupta/Matrices/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Dimensions
 A matrix with 𝑚 rows and n columns is said to be an m×n matrix. The entry in the i-th row and j-th column of a matrix A is denoted as Aij.

## Rows and Columns:

**Rows:** The horizontal lines in a matrix. Each row consists of elements arranged horizontally.

**Columns:** The vertical lines in a matrix. Each column consists of elements arranged vertically.

## Matrix Notation:

A matrix with m rows and n columns is represented as an m×n matrix.

## Special Cases:

**Square Matrix:** When m=n, i.e., the number of rows equals the number of columns.

**Row Vector:** A matrix with only one row, denoted as 1×n.

**Column Vector:** A matrix with only one column, denoted as m×1.


In [2]:
import numpy as np

### Creating Matrices

In [3]:
# Example matrices

A = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2 matrix
B = np.array([[1, 2, 3], [4, 5, 6]])    # 2x3 matrix
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 3x3 matrix


In [12]:
print("3 x 2 Matrix A:\n", A)

3 x 2 Matrix A:
 [[1 2]
 [3 4]
 [5 6]]


In [11]:
print("2 x 3 Matrix B:\n", B)

2 x 3 Matrix B:
 [[1 2 3]
 [4 5 6]]


In [10]:
print("3 x 3 Matrix C:\n", C)

3 x 3 Matrix C:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Checking Dimensions

To check the dimensions of a matrix, use the .shape attribute:

In [13]:
print("Dimensions of A:", A.shape)  # Output: (3, 2)
print("Dimensions of B:", B.shape)  # Output: (2, 3)
print("Dimensions of C:", C.shape)  # Output: (3, 3)


Dimensions of A: (3, 2)
Dimensions of B: (2, 3)
Dimensions of C: (3, 3)


# Types of Matrices


## Square Matrix :
 A square matrix has an equal number of rows and columns

In [14]:

# Create a square matrix
square_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Square Matrix:\n", square_matrix)


Square Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Diagonal Matrix:
A diagonal matrix is a square matrix where all off-diagonal elements are zero.

In [15]:
# Create a diagonal matrix
diagonal_matrix = np.diag([1, 2, 3])
print("Diagonal Matrix:\n", diagonal_matrix)


Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


## Identity Matrix:
An identity matrix is a special diagonal matrix where all diagonal elements are 1.

In [16]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Upper Triangular Matrix:
An upper triangular matrix has zeros below the main diagonal.

In [17]:
# Create an upper triangular matrix
upper_triangular_matrix = np.array([[1, 2, 3], [0, 4, 5], [0, 0, 6]])
print("Upper Triangular Matrix:\n", upper_triangular_matrix)


Upper Triangular Matrix:
 [[1 2 3]
 [0 4 5]
 [0 0 6]]


## Lower Triangular Matrix:
A lower triangular matrix has zeros above the main diagonal.

In [18]:
# Create a lower triangular matrix
lower_triangular_matrix = np.array([[1, 0, 0], [2, 3, 0], [4, 5, 6]])
print("Lower Triangular Matrix:\n", lower_triangular_matrix)


Lower Triangular Matrix:
 [[1 0 0]
 [2 3 0]
 [4 5 6]]


## Symmetric Matrix:
A symmetric matrix is equal to its transpose.

In [19]:
# Create a symmetric matrix
symmetric_matrix = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
print("Symmetric Matrix:\n", symmetric_matrix)


Symmetric Matrix:
 [[1 2 3]
 [2 4 5]
 [3 5 6]]


## Zero Matrix:
 A zero matrix has all elements equal to zero.

In [20]:
# Create a zero matrix
zero_matrix = np.zeros((2, 3))
print("Zero Matrix:\n", zero_matrix)


Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]


## Ones Matrix:
An ones matrix has all elements equal to one.

In [21]:
# Create a 3x2 ones matrix
ones_matrix = np.ones((3, 2))
print("Ones Matrix:\n", ones_matrix)


Ones Matrix:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


## Transpose:


In [23]:
# Example matrix
A = np.array([[1, 2, 3], [4, 5, 6]])


In [24]:
# Compute the transpose
A_transposed = A.T

print("Original Matrix A:\n", A)
print("Transpose of A:\n", A_transposed)

Original Matrix A:
 [[1 2 3]
 [4 5 6]]
Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]


# Operations on Matrices

## Addition and Subtraction

In [25]:
# Example matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [27]:
# Addition
C = A + B
print("A + B:\n", C)


A + B:
 [[ 6  8]
 [10 12]]


In [28]:
# Subtraction
D = A - B
print("A - B:\n", D)

A - B:
 [[-4 -4]
 [-4 -4]]


## Scalar Multiplication

In [29]:
# Scalar multiplication
alpha = 2
E = alpha * A
print("alpha * A:\n", E)


alpha * A:
 [[2 4]
 [6 8]]


## Matrix Multiplication

In [30]:
# Example matrices
A = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2 matrix
B = np.array([[7, 8, 9], [10, 11, 12]])  # 2x3 matrix

# Matrix multiplication
F = np.dot(A, B)
print("A * B:\n", F)


A * B:
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


## Transpose

In [31]:
# Example matrix
A = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose
A_transposed = A.T
print("Transpose of A:\n", A_transposed)


Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]


##  Inverse

In [32]:
# Example square matrix
A = np.array([[1, 2], [3, 4]])

# Inverse of A
A_inverse = np.linalg.inv(A)
print("Inverse of A:\n", A_inverse)


Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## Determinant

In [33]:
# Example square matrix
A = np.array([[1, 2], [3, 4]])

# Determinant of A
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)


Determinant of A: -2.0000000000000004


# Properties of Matrices


## Commutativity of Addition:
Matrix addition is commutative, meaning the order of addition does not affect the result.

In [34]:
# Example matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [35]:
# A + B
result1 = A + B

# B + A
result2 = B + A

print("A + B:\n", result1)
print("B + A:\n", result2)

A + B:
 [[ 6  8]
 [10 12]]
B + A:
 [[ 6  8]
 [10 12]]


## Associativity of Addition:
Matrix addition is associative, meaning the grouping of matrices in an addition operation does not affect the result:

In [36]:
# Example matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])

In [38]:
# (A + B) + C
result1 = (A + B) + C

# A + (B + C)
result2 = A + (B + C)

print("(A + B) + C:\n", result1)

print("A + (B + C):\n", result2)

(A + B) + C:
 [[15 18]
 [21 24]]
A + (B + C):
 [[15 18]
 [21 24]]


##  Distributivity of Scalar Multiplication over Addition:
Scalar multiplication distributes over matrix addition

In [39]:
# Example matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
alpha = 2

# alpha * (A + B)
result1 = alpha * (A + B)

# alpha * A + alpha * B
result2 = alpha * A + alpha * B

print("alpha * (A + B):\n", result1)
print("alpha * A + alpha * B:\n", result2)


alpha * (A + B):
 [[12 16]
 [20 24]]
alpha * A + alpha * B:
 [[12 16]
 [20 24]]


## Identity Matrix Property:
Multiplying a matrix by the identity matrix (of appropriate size) leaves the matrix unchanged:

In [40]:
# Example matrix
A = np.array([[1, 2], [3, 4]])

# Identity matrix
I = np.eye(2)

# A * I
result1 = np.dot(A, I)

# I * A
result2 = np.dot(I, A)

print("A * I:\n", result1)
print("I * A:\n", result2)


A * I:
 [[1. 2.]
 [3. 4.]]
I * A:
 [[1. 2.]
 [3. 4.]]


## Inverse Property

In [41]:
# Example square matrix
A = np.array([[1, 2], [3, 4]])

# Inverse of A
A_inverse = np.linalg.inv(A)

# A * A_inverse
result1 = np.dot(A, A_inverse)

# A_inverse * A
result2 = np.dot(A_inverse, A)

print("A * A_inverse:\n", result1)
print("A_inverse * A:\n", result2)


A * A_inverse:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
A_inverse * A:
 [[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]
